base:
  upload-dir: d:\KmDocs
  db-backup-dir: d:\KmDbBackup
  soffice-path: c:\Program Files\LibreOffice\program\soffice.exe
  one-system-url:
esclient:
  master-host: xxxxx
  master-port: 9200
  master-auth: true
  master-user-name: elastic
  master-user-pwd: xxxx
spring:
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://xxxxxx:3306/km_trial?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: xxxxxx
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 9
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: ''
    port: 6379
jeecg:
  uploadType: local
  path :
    upload: /opt/upload
    webapp: /opt/webapp
  oss:
    accessKey: ??
    secretKey: ??
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: ??
    staticDomain: https://static.jeecg.com
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: ??
