##文件上传和转换工具的配置
base:
  #上传文件保存的路径
  upload-dir: /kykms/KmDocs
  db-backup-dir: c:\KmDocs
  # libreOffice安装路径
  soffice-path: /usr/bin/soffice
##ElasticSearch服务配置 for highLevelRestClient
esclient:
  master-host:
  master-port: 9200
  master-auth: true
  master-user-name: elastic
  master-user-pwd:

spring:
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  mail:
    host:
    username:
    password: ??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
    prefer-file-system-access: false
    template-loader-path:
      - classpath:/templates
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 1000
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: -1
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 数据库登录信息配置
        master:
          url: jdbc:oracle:thin:@106.52.244.12:1521:GHYZSK
          username: ZSK
          password: GHYzsk_163com
          driver-class-name: oracle.jdbc.driver.OracleDriver
  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: ''
    port: 6379
jeecg :
  uploadType: local
  path :
    upload: /opt/upload
    webapp: /opt/webapp
  shiro:
     excludeUrls: /test/jeecgDemo/demo3,/test/jeecgDemo/redisDemo/**,/category/**,/visual/**,/map/**,/jmreport/bigscreen2/**,/sys/loginThird,/KM/EsMgnt/**
  oss:
    accessKey: ??
    secretKey: ??
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: ??
    staticDomain: https://static.jeecg.com
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: ??
  xxljob:
    enabled: false
    adminAddresses: http://127.0.0.1:9080/xxl-job-admin
    appname: ${spring.application.name}
    accessToken: ''
    address: 127.0.0.1:30007
    ip: 127.0.0.1
    port: 30007
    logPath: logs/jeecg/job/jobhandler/
    logRetentionDays: 30
  route:
    config:
      data-id: jeecg-gateway-router
      group: DEFAULT_GROUP
      data-type: yml
  redisson:
    address: 127.0.0.1:6379
    password:
    type: STANDALONE
    enabled: true
cas:
  prefixUrl: http://cas.example.org:8443/cas
logging:
  level:
    org.jeecg.modules.system.mapper : info
knife4j:
  production: false
  basic:
    enable: true
    username: jeecg
    password: jeecg1314
