## 商业版试用镜像提供源下载，仅限于个人学习用途，如擅自用于商业用途，带来的一切后果由个人负责
## !!!!暂未完善，如有需求请联系作者!!!!!
##执行启动命令 docker-compose -f ./docker-compose-business_web.yml up
version: '2'
services:
  kykms-nginx:
    image: mahonelau/kykms-nginx:business_official
    restart: always
    container_name: kykms-nginx
    ports:
    - 80:80